name: Run E2E and RPC Tests

on:
  pull_request:    

jobs:
  parseoutput:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: "true"
      name: Check out code

    - name: Check whats mounted
      run: docker run -v ${{ github.workspace }}:/work busybox ls -lah /work

    - name: Create a files
      run: docker run -v ${{ github.workspace }}:/work busybox touch /work/results.xml
    - name: Check whats in the workspace again
      run: ls -lah

    - uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: output.xml